// ============================================================
// numerology.js — Numerology Engine
// Life path, expression, personal day/year calculations
// ============================================================

const Numerology = {

  // ── Reduce to Single Digit (or Master Number) ─────────────
  reduce(num) {
    // Master numbers: 11, 22, 33 are not reduced
    if (num === 11 || num === 22 || num === 33) return num;
    while (num > 9) {
      num = String(num).split('').reduce((a, b) => a + parseInt(b), 0);
      if (num === 11 || num === 22 || num === 33) return num;
    }
    return num;
  },

  // ── Life Path Number ──────────────────────────────────────
  // The most important number — derived from full date of birth
  getLifePath(year, month, day) {
    const m = this.reduce(month);
    const d = this.reduce(day);
    const y = this.reduce(year);
    return this.reduce(m + d + y);
  },

  // ── Personal Year Number ──────────────────────────────────
  // Current year's energy cycle (1-9)
  getPersonalYear(birthMonth, birthDay, currentYear = new Date().getFullYear()) {
    const m = this.reduce(birthMonth);
    const d = this.reduce(birthDay);
    const y = this.reduce(currentYear);
    return this.reduce(m + d + y);
  },

  // ── Personal Month Number ─────────────────────────────────
  getPersonalMonth(birthMonth, birthDay, date = new Date()) {
    const personalYear = this.getPersonalYear(birthMonth, birthDay, date.getFullYear());
    const currentMonth = this.reduce(date.getMonth() + 1);
    return this.reduce(personalYear + currentMonth);
  },

  // ── Personal Day Number ───────────────────────────────────
  getPersonalDay(birthMonth, birthDay, date = new Date()) {
    const personalMonth = this.getPersonalMonth(birthMonth, birthDay, date);
    const currentDay = this.reduce(date.getDate());
    return this.reduce(personalMonth + currentDay);
  },

  // ── Universal Day Number ──────────────────────────────────
  // The energy of the day for everyone
  getUniversalDay(date = new Date()) {
    const sum = (date.getMonth() + 1) + date.getDate() + date.getFullYear();
    return this.reduce(sum);
  },

  // ── Pythagorean Letter Values ─────────────────────────────
  // A=1, B=2, C=3, D=4, E=5, F=6, G=7, H=8, I=9, J=1, K=2...
  _letterValue(char) {
    const c = char.toUpperCase();
    if (c >= 'A' && c <= 'Z') {
      return ((c.charCodeAt(0) - 65) % 9) + 1;
    }
    return 0;
  },

  _isVowel(char) {
    return 'AEIOU'.includes(char.toUpperCase());
  },

  // ── Name to number (sum all letters, reduce) ───────────────
  _nameToNumber(name) {
    const letters = name.replace(/[^a-zA-Z]/g, '');
    const sum = letters.split('').reduce((acc, c) => acc + this._letterValue(c), 0);
    return this.reduce(sum || 1); // fallback to 1 if sum is 0
  },

  // ── Expression Number (full name — all letters) ────────────
  // Reveals your natural abilities, talents, and life purpose
  getExpressionNumber(fullName) {
    return this._nameToNumber(fullName);
  },

  // ── Soul Urge Number (vowels only) ─────────────────────────
  // Your inner desires, motivations, and heart's deepest longings
  getSoulUrge(fullName) {
    const vowels = fullName.replace(/[^a-zA-Z]/g, '').split('').filter(c => this._isVowel(c)).join('');
    return this._nameToNumber(vowels);
  },

  // ── Personality Number (consonants only) ───────────────────
  // How the world sees you — your outer persona
  getPersonalityNumber(fullName) {
    const consonants = fullName.replace(/[^a-zA-Z]/g, '').split('').filter(c => !this._isVowel(c)).join('');
    return this._nameToNumber(consonants);
  },

  // ── Name Numerology Meanings ───────────────────────────────
  expressionMeanings: {
    1: { en: 'A born leader with originality and drive. Your life path is about initiating — you\'re here to start things, champion ideas, and carve paths others haven\'t imagined. Independence isn\'t a preference; it\'s a requirement for your fullest expression.', fr: 'Un leader né avec originalité et détermination. Votre chemin de vie consiste à initier — vous êtes ici pour lancer des projets, défendre des idées et tracer des voies inédites. L\'indépendance n\'est pas une préférence, c\'est une nécessité pour votre pleine expression.', es: 'Un líder nato con originalidad y determinación. Tu camino de vida consiste en iniciar — estás aquí para empezar cosas, defender ideas y abrir caminos que nadie ha imaginado. La independencia no es una preferencia, es un requisito para tu expresión plena.' },
    2: { en: 'A natural diplomat and peacemaker. You perceive the currents between people that others miss — the unspoken tension, the hidden need. Your gift is making others feel heard. Relationships aren\'t a part of your life; they are the medium through which your life takes shape.', fr: 'Un diplomate et pacificateur naturel. Vous percevez les courants entre les gens que d\'autres manquent — la tension non dite, le besoin caché. Votre don est de faire sentir aux autres qu\'ils sont entendus. Les relations ne font pas partie de votre vie, elles sont le medium à travers lequel votre vie prend forme.', es: 'Un diplomático y pacificador natural. Percibes las corrientes entre personas que otros no ven — la tensión no dicha, la necesidad oculta. Tu don es hacer que otros se sientan escuchados. Las relaciones no son parte de tu vida, son el medio a través del cual tu vida toma forma.' },
    3: { en: 'A creative communicator and joyful spirit. Words, images, and ideas flow through you more easily than through most. You\'re here to make the invisible visible — to give form to what others feel but can\'t articulate. Your challenge is depth: the sparkle comes naturally, but the substance requires discipline.', fr: 'Un communicateur créatif et esprit joyeux. Les mots, images et idées coulent à travers vous plus facilement qu\'à travers la plupart. Vous êtes ici pour rendre visible l\'invisible — donner forme à ce que les autres ressentent mais ne peuvent articuler. Votre défi est la profondeur : l\'éclat vient naturellement, mais la substance demande de la discipline.', es: 'Un comunicador creativo y espíritu alegre. Las palabras, imágenes e ideas fluyen a través de ti más fácilmente que en la mayoría. Estás aquí para hacer visible lo invisible — dar forma a lo que otros sienten pero no pueden articular. Tu desafío es la profundidad: el brillo viene naturalmente, pero la sustancia requiere disciplina.' },
    4: { en: 'A practical builder who creates lasting foundations. Where others dream, you construct. Your mind naturally organizes chaos into systems, plans into timelines, ideas into executable steps. The world needs your steadiness — but remember that foundations exist to support something beautiful, not to be the whole structure.', fr: 'Un bâtisseur pratique qui crée des fondations durables. Là où d\'autres rêvent, vous construisez. Votre esprit organise naturellement le chaos en systèmes, les plans en calendriers, les idées en étapes. Le monde a besoin de votre constance — mais rappelez-vous que les fondations existent pour soutenir quelque chose de beau, pas pour être toute la structure.', es: 'Un constructor práctico que crea bases duraderas. Donde otros sueñan, tú construyes. Tu mente organiza naturalmente el caos en sistemas, los planes en cronogramas, las ideas en pasos ejecutables. El mundo necesita tu constancia — pero recuerda que los cimientos existen para sostener algo hermoso, no para ser toda la estructura.' },
    5: { en: 'A freedom-seeker drawn to adventure and change. You learn through experience, not instruction — your education is the road itself. Restlessness isn\'t a flaw; it\'s your compass pointing toward the next lesson. The challenge is knowing when movement is growth and when it\'s avoidance.', fr: 'Un chercheur de liberté attiré par l\'aventure et le changement. Vous apprenez par l\'expérience, pas par l\'instruction — votre éducation est la route elle-même. L\'agitation n\'est pas un défaut, c\'est votre boussole pointant vers la prochaine leçon. Le défi est de savoir quand le mouvement est croissance et quand c\'est de l\'évitement.', es: 'Un buscador de libertad atraído por la aventura y el cambio. Aprendes por experiencia, no por instrucción — tu educación es el camino mismo. La inquietud no es un defecto, es tu brújula apuntando hacia la próxima lección. El desafío es saber cuándo el movimiento es crecimiento y cuándo es evasión.' },
    6: { en: 'A nurturing soul devoted to love and responsibility. You feel the weight of others\' needs as if they were your own — and you carry it willingly. Home, family, and community are where your power lives. Your lesson is learning that caring for yourself isn\'t selfish; it\'s the source from which all your giving flows.', fr: 'Une âme bienveillante dévouée à l\'amour et la responsabilité. Vous ressentez le poids des besoins des autres comme s\'ils étaient les vôtres — et vous le portez volontiers. Le foyer, la famille et la communauté sont où vit votre pouvoir. Votre leçon est d\'apprendre que prendre soin de soi n\'est pas égoïste, c\'est la source de tout ce que vous donnez.', es: 'Un alma protectora dedicada al amor y la responsabilidad. Sientes el peso de las necesidades de otros como si fueran tuyas — y lo cargas voluntariamente. El hogar, la familia y la comunidad son donde vive tu poder. Tu lección es aprender que cuidar de ti no es egoísmo, es la fuente de todo lo que das.' },
    7: { en: 'A seeker of truth and spiritual wisdom. Your mind works differently — you need to understand why before you can accept what. Surface explanations insult your intelligence. Solitude isn\'t loneliness for you; it\'s where your best thinking happens. The risk is building walls where you only meant to build a quiet room.', fr: 'Un chercheur de vérité et de sagesse spirituelle. Votre esprit fonctionne différemment — vous devez comprendre pourquoi avant d\'accepter quoi. Les explications superficielles insultent votre intelligence. La solitude n\'est pas la solitude pour vous, c\'est là où votre meilleure réflexion se produit. Le risque est de construire des murs là où vous ne vouliez qu\'une pièce tranquille.', es: 'Un buscador de verdad y sabiduría espiritual. Tu mente funciona diferente — necesitas entender el porqué antes de aceptar el qué. Las explicaciones superficiales insultan tu inteligencia. La soledad no es aislamiento para ti, es donde ocurre tu mejor pensamiento. El riesgo es construir muros donde solo querías un cuarto tranquilo.' },
    8: { en: 'A powerhouse of ambition and material mastery. You understand how the world works — power, money, influence — with an instinct others lack. Success comes naturally when you align effort with integrity. Your lesson is remembering that authority is a tool, not an identity, and that the most lasting power is the kind others grant you willingly.', fr: 'Une force d\'ambition et de maîtrise matérielle. Vous comprenez comment le monde fonctionne — pouvoir, argent, influence — avec un instinct que d\'autres n\'ont pas. Le succès vient naturellement quand vous alignez effort et intégrité. Votre leçon est de vous rappeler que l\'autorité est un outil, pas une identité, et que le pouvoir le plus durable est celui que les autres vous accordent librement.', es: 'Una fuerza de ambición y dominio material. Comprendes cómo funciona el mundo — poder, dinero, influencia — con un instinto que otros no tienen. El éxito viene naturalmente cuando alineas esfuerzo con integridad. Tu lección es recordar que la autoridad es una herramienta, no una identidad, y que el poder más duradero es el que otros te conceden libremente.' },
    9: { en: 'A compassionate humanitarian with universal vision. You see the larger pattern — the suffering that connects strangers, the beauty that transcends borders. Your empathy is vast but it needs grounding, or it becomes grief without action. You\'re here to complete and release, not to accumulate. What you give away defines you more than what you keep.', fr: 'Un humanitaire compatissant avec une vision universelle. Vous voyez le schéma plus large — la souffrance qui relie les étrangers, la beauté qui transcende les frontières. Votre empathie est vaste mais elle a besoin d\'ancrage, sinon elle devient chagrin sans action. Vous êtes ici pour achever et libérer, pas pour accumuler. Ce que vous donnez vous définit plus que ce que vous gardez.', es: 'Un humanitario compasivo con visión universal. Ves el patrón más amplio — el sufrimiento que conecta a extraños, la belleza que trasciende fronteras. Tu empatía es vasta pero necesita anclaje, o se convierte en duelo sin acción. Estás aquí para completar y liberar, no para acumular. Lo que das te define más que lo que guardas.' },
    11: { en: 'An illuminated visionary channeling higher truth. You sense things before they arrive — ideas, shifts, undercurrents that haven\'t surfaced yet. This is a Master Number, and it carries weight: the intuition is a gift, but the nervous energy that accompanies it is the cost. Your task is learning to trust the signal without being overwhelmed by the static.', fr: 'Un visionnaire illuminé canalisant la vérité supérieure. Vous sentez les choses avant qu\'elles n\'arrivent — idées, changements, courants qui n\'ont pas encore fait surface. C\'est un Nombre Maître, et il porte un poids : l\'intuition est un don, mais l\'énergie nerveuse qui l\'accompagne en est le coût. Votre tâche est d\'apprendre à faire confiance au signal sans être submergé par le bruit.', es: 'Un visionario iluminado canalizando verdad superior. Sientes las cosas antes de que lleguen — ideas, cambios, corrientes que aún no han salido a la superficie. Es un Número Maestro, y lleva peso: la intuición es un don, pero la energía nerviosa que la acompaña es el costo. Tu tarea es aprender a confiar en la señal sin ser abrumado por el ruido.' },
    22: { en: 'A master architect who builds dreams into reality. Where the 4 builds foundations and the 11 receives visions, you do both — and at scale. This is the rarest practical gift in numerology: the ability to see what doesn\'t exist yet and construct it in the real world. The burden is that ordinary ambitions will never satisfy you.', fr: 'Un architecte maître qui construit les rêves en réalité. Là où le 4 construit des fondations et le 11 reçoit des visions, vous faites les deux — et à grande échelle. C\'est le don pratique le plus rare en numérologie : la capacité de voir ce qui n\'existe pas encore et de le construire dans le monde réel. Le fardeau est que les ambitions ordinaires ne vous satisferont jamais.', es: 'Un arquitecto maestro que construye sueños en realidad. Donde el 4 construye cimientos y el 11 recibe visiones, tú haces ambos — y a gran escala. Es el don práctico más raro en numerología: la capacidad de ver lo que aún no existe y construirlo en el mundo real. La carga es que las ambiciones ordinarias nunca te satisfarán.' },
    33: { en: 'A master teacher radiating unconditional love. The 33 is the rarest Expression Number — most people never encounter one. Your presence is felt before your words are heard. You teach not through instruction but through being. The challenge is that the world will always ask more of you than you have to give, and you must learn to say no without guilt.', fr: 'Un maître enseignant rayonnant d\'amour inconditionnel. Le 33 est le Nombre d\'Expression le plus rare — la plupart des gens n\'en rencontrent jamais. Votre présence est ressentie avant que vos mots ne soient entendus. Vous enseignez non par l\'instruction mais par l\'être. Le défi est que le monde vous demandera toujours plus que ce que vous avez à donner, et vous devez apprendre à dire non sans culpabilité.', es: 'Un maestro irradiando amor incondicional. El 33 es el Número de Expresión más raro — la mayoría nunca encuentra uno. Tu presencia se siente antes de que tus palabras se escuchen. Enseñas no a través de la instrucción sino del ser. El desafío es que el mundo siempre te pedirá más de lo que puedes dar, y debes aprender a decir no sin culpa.' }
  },

  soulUrgeMeanings: {
    1: { en: 'To lead, to pioneer, to be first. Beneath everything you do runs a deep need to forge your own path. You\'re not content following someone else\'s vision — you need to create your own, even when the easier road is conformity.', fr: 'Diriger, innover, être premier. Sous tout ce que vous faites coule un besoin profond de forger votre propre chemin. Vous n\'êtes pas satisfait de suivre la vision d\'un autre — vous devez créer la vôtre, même quand le chemin le plus facile est la conformité.', es: 'Liderar, pionear, ser el primero. Bajo todo lo que haces corre una necesidad profunda de forjar tu propio camino. No te conformas con seguir la visión de otro — necesitas crear la tuya, incluso cuando el camino fácil es la conformidad.' },
    2: { en: 'To love, to find harmony, to connect. What drives you at the deepest level is the need to belong — not in a crowd, but in a bond. One real connection means more to you than a hundred casual ones. Your inner world craves peace, and discord cuts deeper than others realize.', fr: 'Aimer, trouver l\'harmonie, se connecter. Ce qui vous anime au plus profond est le besoin d\'appartenir — pas dans une foule, mais dans un lien. Une vraie connexion compte plus pour vous que cent relations superficielles. Votre monde intérieur aspire à la paix, et la discorde vous blesse plus que les autres ne le réalisent.', es: 'Amar, encontrar armonía, conectar. Lo que te impulsa al nivel más profundo es la necesidad de pertenecer — no en una multitud, sino en un vínculo. Una conexión real significa más para ti que cien casuales. Tu mundo interior anhela paz, y la discordia te hiere más de lo que otros imaginan.' },
    3: { en: 'To create, to express, to inspire joy. Your soul is restless until it finds an outlet — a canvas, a page, a conversation, a stage. The creative impulse isn\'t a hobby for you; it\'s as necessary as breathing. When you suppress it, everything else in your life suffers.', fr: 'Créer, s\'exprimer, inspirer la joie. Votre âme est agitée jusqu\'à ce qu\'elle trouve un exutoire — une toile, une page, une conversation, une scène. L\'impulsion créative n\'est pas un loisir pour vous, c\'est aussi nécessaire que respirer. Quand vous la supprimez, tout le reste de votre vie en souffre.', es: 'Crear, expresar, inspirar alegría. Tu alma está inquieta hasta que encuentra una salida — un lienzo, una página, una conversación, un escenario. El impulso creativo no es un pasatiempo para ti, es tan necesario como respirar. Cuando lo suprimes, todo lo demás en tu vida sufre.' },
    4: { en: 'To build, to stabilize, to protect. Your deepest need is for solid ground — not just physically, but emotionally. You crave order, predictability, and the knowledge that what you\'ve built will endure. Chaos isn\'t exciting to you; it\'s threatening. Your work is learning that safety can coexist with spontaneity.', fr: 'Construire, stabiliser, protéger. Votre besoin le plus profond est d\'un sol solide — pas seulement physiquement, mais émotionnellement. Vous aspirez à l\'ordre, la prévisibilité et la certitude que ce que vous avez construit perdurera. Le chaos n\'est pas excitant pour vous, il est menaçant. Votre travail est d\'apprendre que la sécurité peut coexister avec la spontanéité.', es: 'Construir, estabilizar, proteger. Tu necesidad más profunda es de suelo firme — no solo físicamente, sino emocionalmente. Anhelas orden, previsibilidad y la certeza de que lo que has construido perdurará. El caos no es emocionante para ti, es amenazante. Tu trabajo es aprender que la seguridad puede coexistir con la espontaneidad.' },
    5: { en: 'To explore, to experience, to be free. Your soul revolts against confinement of any kind — routines, expectations, even your own habits. You need to taste life directly, not read about it. The deepest version of this urge isn\'t restlessness; it\'s a hunger to understand what it means to be alive through firsthand encounter.', fr: 'Explorer, expérimenter, être libre. Votre âme se révolte contre tout confinement — routines, attentes, même vos propres habitudes. Vous avez besoin de goûter la vie directement, pas de lire à son sujet. La version la plus profonde de cette envie n\'est pas l\'agitation, c\'est une faim de comprendre ce que signifie être vivant à travers l\'expérience directe.', es: 'Explorar, experimentar, ser libre. Tu alma se rebela contra todo confinamiento — rutinas, expectativas, incluso tus propios hábitos. Necesitas probar la vida directamente, no leer sobre ella. La versión más profunda de este impulso no es inquietud, es un hambre de entender qué significa estar vivo a través del encuentro directo.' },
    6: { en: 'To nurture, to heal, to serve loved ones. At your core, you need to be needed. The people you love are not separate from your identity — their wellbeing is woven into yours. This makes you capable of extraordinary devotion, but also vulnerable to losing yourself in someone else\'s story.', fr: 'Nourrir, guérir, servir les êtres chers. Au fond de vous, vous avez besoin qu\'on ait besoin de vous. Les personnes que vous aimez ne sont pas séparées de votre identité — leur bien-être est tissé dans le vôtre. Cela vous rend capable d\'un dévouement extraordinaire, mais aussi vulnérable à vous perdre dans l\'histoire de quelqu\'un d\'autre.', es: 'Nutrir, sanar, servir a los seres queridos. En tu esencia, necesitas ser necesitado. Las personas que amas no están separadas de tu identidad — su bienestar está tejido en el tuyo. Esto te hace capaz de una devoción extraordinaria, pero también vulnerable a perderte en la historia de otro.' },
    7: { en: 'To understand, to seek truth, to find inner peace. Your soul won\'t rest until it makes sense of things — not superficially, but at the level of meaning. You\'re driven by questions others don\'t think to ask. The cost is that easy answers will never satisfy you, and the search can become lonelier than it needs to be.', fr: 'Comprendre, chercher la vérité, trouver la paix intérieure. Votre âme ne se reposera pas tant qu\'elle n\'aura pas donné un sens aux choses — pas superficiellement, mais au niveau du sens profond. Vous êtes poussé par des questions que d\'autres ne pensent pas à poser. Le coût est que les réponses faciles ne vous satisferont jamais, et la recherche peut devenir plus solitaire qu\'elle ne devrait.', es: 'Comprender, buscar la verdad, encontrar paz interior. Tu alma no descansará hasta que las cosas tengan sentido — no superficialmente, sino al nivel del significado. Te impulsan preguntas que otros no piensan en hacer. El costo es que las respuestas fáciles nunca te satisfarán, y la búsqueda puede volverse más solitaria de lo necesario.' },
    8: { en: 'To achieve, to master, to attain abundance. What drives you isn\'t greed — it\'s the need to prove that your vision can take material form. You want to build something real, something you can point to and say: I made that happen. The inner work is separating your self-worth from your net worth.', fr: 'Accomplir, maîtriser, atteindre l\'abondance. Ce qui vous anime n\'est pas la cupidité — c\'est le besoin de prouver que votre vision peut prendre une forme matérielle. Vous voulez construire quelque chose de réel, quelque chose que vous pouvez montrer et dire : j\'ai fait ça. Le travail intérieur est de séparer votre valeur personnelle de votre valeur nette.', es: 'Lograr, dominar, alcanzar la abundancia. Lo que te impulsa no es la codicia — es la necesidad de probar que tu visión puede tomar forma material. Quieres construir algo real, algo que puedas señalar y decir: yo hice que esto sucediera. El trabajo interior es separar tu valor personal de tu valor neto.' },
    9: { en: 'To serve humanity, to heal, to release. Your deepest motivation isn\'t personal success — it\'s contribution. You feel the suffering of the world as a personal weight, and you\'re driven to lighten it. The lesson embedded in this urge is that you cannot save everyone, and that releasing the need to do so is itself an act of service.', fr: 'Servir l\'humanité, guérir, libérer. Votre motivation la plus profonde n\'est pas le succès personnel — c\'est la contribution. Vous ressentez la souffrance du monde comme un poids personnel, et vous êtes poussé à l\'alléger. La leçon dans cet élan est que vous ne pouvez pas sauver tout le monde, et que renoncer au besoin de le faire est lui-même un acte de service.', es: 'Servir a la humanidad, sanar, liberar. Tu motivación más profunda no es el éxito personal — es la contribución. Sientes el sufrimiento del mundo como un peso personal, y te impulsa aligerarlo. La lección en este impulso es que no puedes salvar a todos, y que soltar la necesidad de hacerlo es en sí un acto de servicio.' },
    11: { en: 'To illuminate, to inspire, to awaken others. Your inner world is electric — intuitions arrive like lightning, not like logic. You\'re here to channel something larger than yourself, and the urge to do so can feel like a calling you didn\'t choose. The work is learning to ground the voltage without dimming it.', fr: 'Illuminer, inspirer, éveiller les autres. Votre monde intérieur est électrique — les intuitions arrivent comme des éclairs, pas comme de la logique. Vous êtes ici pour canaliser quelque chose de plus grand que vous, et l\'envie de le faire peut ressembler à un appel que vous n\'avez pas choisi. Le travail est d\'apprendre à ancrer le voltage sans l\'atténuer.', es: 'Iluminar, inspirar, despertar a otros. Tu mundo interior es eléctrico — las intuiciones llegan como relámpagos, no como lógica. Estás aquí para canalizar algo más grande que tú, y el impulso de hacerlo puede sentirse como un llamado que no elegiste. El trabajo es aprender a anclar el voltaje sin apagarlo.' },
    22: { en: 'To transform the world through vision and action. Your soul won\'t settle for imagining a better world — it demands that you build one. This is the most ambitious Soul Urge in numerology, and it carries a proportional weight. The inner tension is between the enormity of what you see and the patience required to construct it.', fr: 'Transformer le monde par la vision et l\'action. Votre âme ne se contentera pas d\'imaginer un monde meilleur — elle exige que vous en construisiez un. C\'est le désir de l\'âme le plus ambitieux en numérologie, et il porte un poids proportionnel. La tension intérieure est entre l\'énormité de ce que vous voyez et la patience requise pour le construire.', es: 'Transformar el mundo con visión y acción. Tu alma no se conformará con imaginar un mundo mejor — exige que construyas uno. Es el impulso del alma más ambicioso en numerología, y lleva un peso proporcional. La tensión interior está entre la enormidad de lo que ves y la paciencia requerida para construirlo.' },
    33: { en: 'To uplift all through boundless compassion. Your soul feels the pain of the world and responds not with despair but with love. This is the healer\'s urge at its most refined — not fixing, but holding space. The danger is that boundless compassion without boundaries becomes self-destruction.', fr: 'Élever tous par une compassion sans limites. Votre âme ressent la douleur du monde et répond non par le désespoir mais par l\'amour. C\'est l\'élan du guérisseur à son plus raffiné — pas réparer, mais tenir l\'espace. Le danger est qu\'une compassion sans limites sans frontières devient auto-destruction.', es: 'Elevar a todos con compasión sin límites. Tu alma siente el dolor del mundo y responde no con desesperación sino con amor. Es el impulso del sanador en su forma más refinada — no arreglar, sino sostener el espacio. El peligro es que la compasión sin límites sin fronteras se convierte en autodestrucción.' }
  },

  personalityMeanings: {
    1: { en: 'Confident and self-assured. Others see you as someone who knows where they\'re going, even when you don\'t. You project independence — people hesitate to offer you help because you look like you don\'t need it. This can be a strength or a wall, depending on whether you chose it.', fr: 'Confiant et sûr de soi. Les autres vous voient comme quelqu\'un qui sait où il va, même quand ce n\'est pas le cas. Vous projetez l\'indépendance — les gens hésitent à vous offrir de l\'aide parce que vous semblez ne pas en avoir besoin. Cela peut être une force ou un mur, selon que vous l\'ayez choisi.', es: 'Seguro y confiado. Otros te ven como alguien que sabe a dónde va, incluso cuando no lo sabes. Proyectas independencia — la gente duda en ofrecerte ayuda porque pareces no necesitarla. Esto puede ser una fortaleza o un muro, dependiendo de si lo elegiste.' },
    2: { en: 'Gentle and approachable. People open up to you quickly — there\'s something in your presence that says "it\'s safe here." You come across as a listener, someone without sharp edges. The risk is that others may underestimate your strength because your softness is what they see first.', fr: 'Doux et accessible. Les gens s\'ouvrent à vous rapidement — il y a quelque chose dans votre présence qui dit « c\'est sûr ici ». Vous donnez l\'impression d\'être un auditeur, quelqu\'un sans arêtes vives. Le risque est que les autres sous-estiment votre force parce que votre douceur est ce qu\'ils voient en premier.', es: 'Gentil y accesible. La gente se abre contigo rápidamente — hay algo en tu presencia que dice "aquí es seguro." Pareces un oyente, alguien sin bordes afilados. El riesgo es que otros subestimen tu fuerza porque tu suavidad es lo que ven primero.' },
    3: { en: 'Charming and expressive. You light up a room without trying — your energy is social, warm, and often funny. People are drawn to your ease with words and your willingness to be seen. The shadow side is that some may see the performance and miss the person behind it.', fr: 'Charmant et expressif. Vous illuminez une pièce sans effort — votre énergie est sociale, chaleureuse et souvent drôle. Les gens sont attirés par votre aisance avec les mots et votre volonté d\'être vu. Le côté ombre est que certains voient le spectacle et manquent la personne derrière.', es: 'Encantador y expresivo. Iluminas una habitación sin intentarlo — tu energía es social, cálida y a menudo graciosa. La gente se siente atraída por tu facilidad con las palabras y tu disposición a ser visto. El lado sombra es que algunos ven la actuación y pierden a la persona detrás.' },
    4: { en: 'Reliable and grounded. Others see you as the person who will actually follow through. You project stability and seriousness — people trust you with their plans, their money, their time. The perception can become a cage if you never let anyone see the part of you that\'s uncertain.', fr: 'Fiable et ancré. Les autres vous voient comme la personne qui ira vraiment jusqu\'au bout. Vous projetez stabilité et sérieux — les gens vous confient leurs plans, leur argent, leur temps. La perception peut devenir une cage si vous ne laissez jamais personne voir la part de vous qui doute.', es: 'Confiable y centrado. Otros te ven como la persona que realmente cumplirá. Proyectas estabilidad y seriedad — la gente te confía sus planes, su dinero, su tiempo. La percepción puede convertirse en una jaula si nunca dejas que nadie vea la parte de ti que es incierta.' },
    5: { en: 'Magnetic and adventurous. You come across as someone who\'s lived — traveled, tried things, collected stories. There\'s an electricity to your presence that makes routine conversations feel more interesting. Others may see you as unpredictable, and they\'re not wrong. The question is whether that unpredictability serves you or scatters you.', fr: 'Magnétique et aventureux. Vous donnez l\'impression d\'avoir vécu — voyagé, essayé des choses, collecté des histoires. Il y a une électricité dans votre présence qui rend les conversations ordinaires plus intéressantes. Les autres peuvent vous voir comme imprévisible, et ils n\'ont pas tort. La question est de savoir si cette imprévisibilité vous sert ou vous disperse.', es: 'Magnético y aventurero. Pareces alguien que ha vivido — viajado, probado cosas, coleccionado historias. Hay una electricidad en tu presencia que hace que las conversaciones rutinarias se sientan más interesantes. Otros pueden verte como impredecible, y no se equivocan. La pregunta es si esa imprevisibilidad te sirve o te dispersa.' },
    6: { en: 'Warm and protective. People sense your caring nature immediately — children, animals, and strangers gravitate to you. You project safety and responsibility. Others see someone they can depend on, which is a gift until it becomes an expectation you can\'t sustain.', fr: 'Chaleureux et protecteur. Les gens sentent immédiatement votre nature bienveillante — les enfants, les animaux et les étrangers gravitent vers vous. Vous projetez sécurité et responsabilité. Les autres voient quelqu\'un sur qui ils peuvent compter, ce qui est un don jusqu\'à ce que cela devienne une attente que vous ne pouvez pas soutenir.', es: 'Cálido y protector. La gente siente tu naturaleza cuidadora inmediatamente — niños, animales y extraños gravitan hacia ti. Proyectas seguridad y responsabilidad. Otros ven a alguien en quien pueden depender, lo cual es un don hasta que se convierte en una expectativa que no puedes sostener.' },
    7: { en: 'Mysterious and contemplative. Others sense depth in you — you don\'t reveal everything, and that restraint creates intrigue. You come across as someone who thinks before speaking, who sees more than they say. Some people find this magnetic; others find it distant. Both are seeing the same quality from different angles.', fr: 'Mystérieux et contemplatif. Les autres sentent une profondeur en vous — vous ne révélez pas tout, et cette retenue crée l\'intrigue. Vous donnez l\'impression de quelqu\'un qui réfléchit avant de parler, qui voit plus qu\'il ne dit. Certains trouvent cela magnétique, d\'autres distant. Les deux voient la même qualité sous des angles différents.', es: 'Misterioso y contemplativo. Otros sienten profundidad en ti — no revelas todo, y esa reserva crea intriga. Pareces alguien que piensa antes de hablar, que ve más de lo que dice. Algunos encuentran esto magnético; otros lo encuentran distante. Ambos ven la misma cualidad desde ángulos diferentes.' },
    8: { en: 'Powerful and authoritative. You walk into a room and people make space — not out of fear, but out of recognition. There\'s a weight to your presence that commands respect. Others see competence, ambition, and control. The work is making sure the authority you project is backed by the substance you carry.', fr: 'Puissant et autoritaire. Vous entrez dans une pièce et les gens font de la place — pas par peur, mais par reconnaissance. Il y a un poids dans votre présence qui commande le respect. Les autres voient compétence, ambition et maîtrise. Le travail est de s\'assurer que l\'autorité que vous projetez est soutenue par la substance que vous portez.', es: 'Poderoso y autoritario. Entras a una habitación y la gente hace espacio — no por miedo, sino por reconocimiento. Hay un peso en tu presencia que impone respeto. Otros ven competencia, ambición y control. El trabajo es asegurar que la autoridad que proyectas esté respaldada por la sustancia que llevas.' },
    9: { en: 'Worldly and compassionate. Others see someone who\'s been shaped by experience — cultured, understanding, tolerant. You project a kind of wise acceptance that makes people feel less judged. The risk is that this universal warmth can feel impersonal to those who want to be special to you, not just included in your compassion.', fr: 'Cosmopolite et compatissant. Les autres voient quelqu\'un façonné par l\'expérience — cultivé, compréhensif, tolérant. Vous projetez une acceptation sage qui fait que les gens se sentent moins jugés. Le risque est que cette chaleur universelle peut sembler impersonnelle pour ceux qui veulent être spéciaux pour vous, pas seulement inclus dans votre compassion.', es: 'Cosmopolita y compasivo. Otros ven a alguien moldeado por la experiencia — culto, comprensivo, tolerante. Proyectas una aceptación sabia que hace que la gente se sienta menos juzgada. El riesgo es que esa calidez universal puede sentirse impersonal para quienes quieren ser especiales para ti, no solo incluidos en tu compasión.' },
    11: { en: 'Ethereal and inspiring. There\'s something about you that people can\'t quite name — a quality of being slightly elsewhere, slightly tuned to a different frequency. You inspire without trying. Others sense your sensitivity and either want to protect it or test it. Your presence asks questions that your words don\'t.', fr: 'Éthéré et inspirant. Il y a quelque chose en vous que les gens ne peuvent pas tout à fait nommer — une qualité d\'être légèrement ailleurs, accordé à une fréquence différente. Vous inspirez sans essayer. Les autres sentent votre sensibilité et veulent soit la protéger, soit la tester. Votre présence pose des questions que vos mots ne posent pas.', es: 'Etéreo e inspirador. Hay algo en ti que la gente no puede nombrar del todo — una cualidad de estar ligeramente en otro lugar, sintonizado a una frecuencia diferente. Inspiras sin intentarlo. Otros sienten tu sensibilidad y quieren protegerla o ponerla a prueba. Tu presencia hace preguntas que tus palabras no hacen.' },
    22: { en: 'Commanding and visionary. Others sense that you see further than they do — and that you have the will to act on what you see. You project the rare combination of dreamer and doer. People either want to follow you or get out of your way. The challenge is that this intensity can intimidate before it inspires.', fr: 'Imposant et visionnaire. Les autres sentent que vous voyez plus loin qu\'eux — et que vous avez la volonté d\'agir sur ce que vous voyez. Vous projetez la rare combinaison de rêveur et de faiseur. Les gens veulent soit vous suivre, soit s\'écarter. Le défi est que cette intensité peut intimider avant d\'inspirer.', es: 'Imponente y visionario. Otros sienten que ves más lejos que ellos — y que tienes la voluntad de actuar sobre lo que ves. Proyectas la rara combinación de soñador y hacedor. La gente quiere seguirte o apartarse de tu camino. El desafío es que esa intensidad puede intimidar antes de inspirar.' },
    33: { en: 'Radiant and selfless. Your presence feels like warmth — people relax around you, confide in you, trust you with things they haven\'t told anyone. You project a kind of love that doesn\'t ask for anything in return, and that\'s both your greatest gift and your greatest vulnerability.', fr: 'Rayonnant et altruiste. Votre présence ressemble à de la chaleur — les gens se détendent autour de vous, se confient à vous, vous confient des choses qu\'ils n\'ont dites à personne. Vous projetez un amour qui ne demande rien en retour, et c\'est à la fois votre plus grand don et votre plus grande vulnérabilité.', es: 'Radiante y desinteresado. Tu presencia se siente como calidez — la gente se relaja a tu alrededor, te confía cosas, te cuenta lo que no ha dicho a nadie. Proyectas un amor que no pide nada a cambio, y eso es tanto tu mayor don como tu mayor vulnerabilidad.' }
  },

  // ── Number Meanings (used for Life Path, Personal Day/Month) ───
  meanings: {
    1:  {
      theme: { en: 'New Beginnings & Leadership', fr: 'Nouveaux Départs & Leadership', es: 'Nuevos Comienzos & Liderazgo' },
      energy: { en: 'independence, initiative, originality', fr: 'indépendance, initiative, originalité', es: 'independencia, iniciativa, originalidad' },
      advice: { en: 'Trust your instincts and take the lead today. This is a day of firsts — conversations you initiate, steps you take alone, ideas you champion will carry unusual power. Others may look to you for direction.', fr: 'Faites confiance à vos instincts et prenez les devants. C\'est un jour de premières — les conversations que vous initiez, les pas que vous faites seul, les idées que vous défendez porteront une puissance inhabituelle.', es: 'Confía en tus instintos y toma la iniciativa. Es un día de primeras veces — las conversaciones que inicies, los pasos que des solo, las ideas que defiendas tendrán un poder inusual.' },
      shadow: { en: 'Watch for impatience or a tendency to bulldoze through others. Independence becomes isolation if you refuse all input.', fr: 'Attention à l\'impatience ou à la tendance à écraser les autres. L\'indépendance devient isolement si vous refusez toute contribution.', es: 'Cuidado con la impaciencia o la tendencia a pasar por encima de otros. La independencia se vuelve aislamiento si rechazas toda aportación.' }
    },
    2:  {
      theme: { en: 'Partnership & Balance', fr: 'Partenariat & Équilibre', es: 'Asociación & Equilibrio' },
      energy: { en: 'cooperation, diplomacy, sensitivity', fr: 'coopération, diplomatie, sensibilité', es: 'cooperación, diplomacia, sensibilidad' },
      advice: { en: 'Seek harmony in your connections and be patient. Today favors listening over speaking, compromise over conquest. Pay attention to what others aren\'t saying — your emotional antennae are finely tuned right now.', fr: 'Cherchez l\'harmonie dans vos connexions et soyez patient. Aujourd\'hui favorise l\'écoute plutôt que la parole, le compromis plutôt que la conquête. Vos antennes émotionnelles sont finement réglées.', es: 'Busca la armonía en tus conexiones y sé paciente. Hoy favorece escuchar sobre hablar, el compromiso sobre la conquista. Tus antenas emocionales están finamente sintonizadas.' },
      shadow: { en: 'Avoid losing yourself in others\' needs. People-pleasing can masquerade as diplomacy. Your needs matter too.', fr: 'Évitez de vous perdre dans les besoins des autres. Vouloir plaire peut se déguiser en diplomatie. Vos besoins comptent aussi.', es: 'Evita perderte en las necesidades de otros. Complacer puede disfrazarse de diplomacia. Tus necesidades también importan.' }
    },
    3:  {
      theme: { en: 'Creativity & Expression', fr: 'Créativité & Expression', es: 'Creatividad & Expresión' },
      energy: { en: 'joy, communication, artistic flow', fr: 'joie, communication, flux artistique', es: 'alegría, comunicación, flujo artístico' },
      advice: { en: 'Express yourself freely and embrace creative inspiration. Words come easily today — write, speak, sing, paint. Social energy is high. If you\'ve been holding something back, this is the day to let it out with grace.', fr: 'Exprimez-vous librement et embrassez l\'inspiration créative. Les mots viennent facilement — écrivez, parlez, chantez, peignez. L\'énergie sociale est haute. Si vous retenez quelque chose, c\'est le jour de le laisser sortir avec grâce.', es: 'Exprésate libremente y abraza la inspiración creativa. Las palabras fluyen fácilmente — escribe, habla, canta, pinta. La energía social está alta. Si has estado guardando algo, hoy es el día de dejarlo salir con gracia.' },
      shadow: { en: 'Scattered energy is the risk. Too many projects, too much talking, not enough follow-through. Channel the sparkle, don\'t spray it.', fr: 'L\'énergie dispersée est le risque. Trop de projets, trop de paroles, pas assez de suivi. Canalisez l\'étincelle.', es: 'La energía dispersa es el riesgo. Demasiados proyectos, demasiada charla, poco seguimiento. Canaliza la chispa.' }
    },
    4:  {
      theme: { en: 'Foundation & Structure', fr: 'Fondation & Structure', es: 'Base & Estructura' },
      energy: { en: 'stability, discipline, hard work', fr: 'stabilité, discipline, travail acharné', es: 'estabilidad, disciplina, trabajo duro' },
      advice: { en: 'Build with care and attention to detail. This is not a day for shortcuts — the work you put in now creates something that lasts. Organize, plan, follow through. The boring tasks today are the ones that will matter most tomorrow.', fr: 'Construisez avec soin et attention aux détails. Ce n\'est pas un jour pour les raccourcis — le travail que vous investissez maintenant crée quelque chose de durable. Organisez, planifiez, allez jusqu\'au bout. Les tâches ennuyeuses d\'aujourd\'hui seront les plus importantes demain.', es: 'Construye con cuidado y atención al detalle. No es día de atajos — el trabajo que inviertas ahora crea algo duradero. Organiza, planifica, lleva las cosas hasta el final. Las tareas aburridas de hoy serán las más importantes mañana.' },
      shadow: { en: 'Rigidity is the trap. Being methodical is good; being inflexible is limiting. Leave room for the unexpected.', fr: 'La rigidité est le piège. Être méthodique est bon; être inflexible est limitant. Laissez de la place à l\'imprévu.', es: 'La rigidez es la trampa. Ser metódico es bueno; ser inflexible es limitante. Deja espacio para lo inesperado.' }
    },
    5:  {
      theme: { en: 'Change & Freedom', fr: 'Changement & Liberté', es: 'Cambio & Libertad' },
      energy: { en: 'adventure, versatility, transformation', fr: 'aventure, polyvalence, transformation', es: 'aventura, versatilidad, transformación' },
      advice: { en: 'Embrace change and stay adaptable — adventure calls. Routine will feel suffocating today. Say yes to the unexpected invitation, the spontaneous detour, the idea that makes no logical sense but feels alive.', fr: 'Embrassez le changement et restez adaptable — l\'aventure appelle. La routine sera étouffante. Dites oui à l\'invitation inattendue, au détour spontané, à l\'idée qui ne fait aucun sens logique mais qui se sent vivante.', es: 'Abraza el cambio y mantente adaptable — la aventura llama. La rutina se sentirá sofocante. Di sí a la invitación inesperada, al desvío espontáneo, a la idea que no tiene sentido lógico pero se siente viva.' },
      shadow: { en: 'Restlessness without direction leads to chaos. Freedom doesn\'t mean running from commitment — it means choosing consciously.', fr: 'L\'agitation sans direction mène au chaos. La liberté ne signifie pas fuir l\'engagement — elle signifie choisir consciemment.', es: 'La inquietud sin dirección lleva al caos. La libertad no significa huir del compromiso — significa elegir conscientemente.' }
    },
    6:  {
      theme: { en: 'Love & Responsibility', fr: 'Amour & Responsabilité', es: 'Amor & Responsabilidad' },
      energy: { en: 'nurturing, harmony, domestic matters', fr: 'soin, harmonie, affaires domestiques', es: 'cuidado, armonía, asuntos domésticos' },
      advice: { en: 'Focus on home, heart, and those you care for. Today carries a warm, protective energy. Relationships deepen through small acts of service. A conversation with family or a gesture of care will resonate more than you expect.', fr: 'Concentrez-vous sur le foyer, le cœur et ceux que vous aimez. Aujourd\'hui porte une énergie chaleureuse et protectrice. Les relations s\'approfondissent par de petits actes de service. Une conversation en famille ou un geste d\'attention résonnera plus que vous ne le pensez.', es: 'Enfócate en el hogar, el corazón y quienes te importan. Hoy lleva una energía cálida y protectora. Las relaciones se profundizan con pequeños actos de servicio. Una conversación con la familia o un gesto de cuidado resonará más de lo que esperas.' },
      shadow: { en: 'Martyrdom lurks here. Giving until you\'re empty isn\'t love — it\'s self-abandonment. Care for yourself first.', fr: 'Le martyre guette. Donner jusqu\'à l\'épuisement n\'est pas de l\'amour — c\'est de l\'auto-abandon. Prenez soin de vous d\'abord.', es: 'El martirio acecha. Dar hasta vaciarte no es amor — es auto-abandono. Cuídate a ti primero.' }
    },
    7:  {
      theme: { en: 'Wisdom & Introspection', fr: 'Sagesse & Introspection', es: 'Sabiduría & Introspección' },
      energy: { en: 'spiritual seeking, analysis, solitude', fr: 'quête spirituelle, analyse, solitude', es: 'búsqueda espiritual, análisis, soledad' },
      advice: { en: 'Go within — today\'s wisdom comes from solitude, not from action. The answers you seek won\'t arrive through conversation or research; they\'re already inside you, waiting in the quiet. Pull back from noise, screens, and small talk. Depth over breadth.', fr: 'Tournez-vous vers l\'intérieur — la sagesse d\'aujourd\'hui vient de la solitude, pas de l\'action. Les réponses ne viendront pas du monde extérieur — elles sont déjà en vous, dans le silence. Éloignez-vous du bruit et de la superficialité.', es: 'Ve hacia adentro — la sabiduría de hoy viene de la soledad, no de la acción. Las respuestas no vendrán del mundo exterior — ya están dentro de ti, en el silencio. Aléjate del ruido y de lo superficial.' },
      shadow: { en: 'Overthinking and emotional withdrawal are the risks. Analysis becomes paralysis when you refuse to act without perfect understanding.', fr: 'La réflexion excessive et le retrait émotionnel sont les risques. L\'analyse devient paralysie quand on refuse d\'agir sans compréhension parfaite.', es: 'Pensar demasiado y el aislamiento emocional son los riesgos. El análisis se vuelve parálisis cuando te niegas a actuar sin comprensión perfecta.' }
    },
    8:  {
      theme: { en: 'Power & Abundance', fr: 'Pouvoir & Abondance', es: 'Poder & Abundancia' },
      energy: { en: 'ambition, manifestation, material success', fr: 'ambition, manifestation, succès matériel', es: 'ambición, manifestación, éxito material' },
      advice: { en: 'Step into your authority — financial and professional matters carry extra weight today. Decisions you make now have staying power, so negotiate, sign, and commit with confidence. The universe backs bold moves right now, especially ones you\'ve prepared for.', fr: 'Assumez votre autorité — les questions financières et professionnelles portent un poids supplémentaire aujourd\'hui. Les décisions que vous prenez maintenant ont un pouvoir durable, alors négociez, signez et engagez-vous avec confiance.', es: 'Asume tu autoridad — los asuntos financieros y profesionales tienen peso extra hoy. Las decisiones que tomes ahora tienen poder duradero, así que negocia, firma y comprométete con confianza.' },
      shadow: { en: 'Power without compassion becomes tyranny. Material focus without soul becomes emptiness. Use your strength to lift, not to control.', fr: 'Le pouvoir sans compassion devient tyrannie. Le focus matériel sans âme devient vide. Utilisez votre force pour élever, pas pour contrôler.', es: 'El poder sin compasión se vuelve tiranía. El enfoque material sin alma se vuelve vacío. Usa tu fuerza para elevar, no para controlar.' }
    },
    9:  {
      theme: { en: 'Completion & Compassion', fr: 'Accomplissement & Compassion', es: 'Completación & Compasión' },
      energy: { en: 'humanitarianism, release, universal love', fr: 'humanitarisme, libération, amour universel', es: 'humanitarismo, liberación, amor universal' },
      advice: { en: 'Let go of what no longer serves you — this is a day of endings that make room for beginnings. Give generously, forgive freely. Whatever you release now clears the path for what comes next. Think beyond your own needs.', fr: 'Laissez aller ce qui ne vous sert plus — c\'est un jour de fins qui font place aux débuts. Donnez généreusement, pardonnez librement. Ce que vous libérez maintenant ouvre la voie à ce qui vient.', es: 'Deja ir lo que ya no te sirve — es un día de finales que abren espacio a comienzos. Da generosamente, perdona libremente. Lo que liberes ahora despeja el camino para lo que viene.' },
      shadow: { en: 'Holding on too tightly to what\'s ending creates suffering. The 9 asks you to release with grace, not cling with fear.', fr: 'S\'accrocher à ce qui se termine crée de la souffrance. Le 9 vous demande de lâcher avec grâce, pas de vous cramponner par peur.', es: 'Aferrarte a lo que termina crea sufrimiento. El 9 te pide soltar con gracia, no aferrarte con miedo.' }
    },
    11: {
      theme: { en: 'Spiritual Illumination', fr: 'Illumination Spirituelle', es: 'Iluminación Espiritual' },
      energy: { en: 'intuition, inspiration, visionary insight', fr: 'intuition, inspiration, vision prophétique', es: 'intuición, inspiración, visión profética' },
      advice: { en: 'Your intuition is heightened — trust the visions that come, even the ones that don\'t make logical sense yet. This is a Master Number day: flashes of insight, synchronicities, and moments of deep knowing are all amplified. Pay attention to dreams, symbols, and gut feelings.', fr: 'Votre intuition est amplifiée — faites confiance aux visions qui viennent, même celles qui n\'ont pas encore de sens logique. C\'est un jour de Nombre Maître : éclairs d\'intuition, synchronicités et moments de connaissance profonde sont tous amplifiés.', es: 'Tu intuición está amplificada — confía en las visiones que lleguen, incluso las que aún no tienen sentido lógico. Es un día de Número Maestro: destellos de intuición, sincronicidades y momentos de conocimiento profundo están todos amplificados.' },
      shadow: { en: 'Nervous energy and anxiety can accompany the 11. Ground yourself through breath and body when the insights feel overwhelming.', fr: 'L\'énergie nerveuse et l\'anxiété peuvent accompagner le 11. Ancrez-vous par la respiration et le corps quand les intuitions deviennent accablantes.', es: 'La energía nerviosa y la ansiedad pueden acompañar al 11. Ancla tu cuerpo con la respiración cuando las intuiciones se vuelvan abrumadoras.' }
    },
    22: {
      theme: { en: 'Master Builder', fr: 'Maître Bâtisseur', es: 'Maestro Constructor' },
      energy: { en: 'large-scale achievement, practical idealism', fr: 'accomplissement à grande échelle, idéalisme pratique', es: 'logro a gran escala, idealismo práctico' },
      advice: { en: 'Dream big and build with purpose — you can manifest the extraordinary. The 22 bridges vision and reality. Whatever you lay foundations for today has the potential to become something remarkable. Think in terms of legacy.', fr: 'Rêvez grand et construisez avec but — vous pouvez manifester l\'extraordinaire. Le 22 relie vision et réalité. Ce que vous fondez aujourd\'hui peut devenir remarquable.', es: 'Sueña en grande y construye con propósito — puedes manifestar lo extraordinario. El 22 conecta visión y realidad. Lo que cimientes hoy puede volverse extraordinario.' },
      shadow: { en: 'The weight of potential can paralyze. Don\'t let the grandeur of the vision prevent you from taking the first small step.', fr: 'Le poids du potentiel peut paralyser. Ne laissez pas la grandeur de la vision empêcher le premier petit pas.', es: 'El peso del potencial puede paralizar. No dejes que la grandeza de la visión impida el primer pequeño paso.' }
    },
    33: {
      theme: { en: 'Master Healer', fr: 'Maître Guérisseur', es: 'Maestro Sanador' },
      energy: { en: 'compassionate service, spiritual teaching', fr: 'service compatissant, enseignement spirituel', es: 'servicio compasivo, enseñanza espiritual' },
      advice: { en: 'Your gift today is healing through love — share your light without holding back. The 33 is the rarest Master Number energy: your presence alone can shift the atmosphere in a room. Teach by example, love without agenda, serve without keeping score.', fr: 'Votre don aujourd\'hui est la guérison par l\'amour — partagez votre lumière sans retenue. Le 33 est l\'énergie la plus rare des Nombres Maîtres : votre seule présence peut changer l\'atmosphère d\'une pièce. Enseignez par l\'exemple, aimez sans condition.', es: 'Tu don hoy es sanar a través del amor — comparte tu luz sin reservas. El 33 es la energía más rara de los Números Maestros: tu sola presencia puede cambiar la atmósfera de una habitación. Enseña con el ejemplo, ama sin condiciones.' },
      shadow: { en: 'The desire to save everyone can become a savior complex. You cannot pour from an empty cup — tend to your own wounds first.', fr: 'Le désir de sauver tout le monde peut devenir un complexe de sauveur. Prenez soin de vos propres blessures d\'abord.', es: 'El deseo de salvar a todos puede volverse complejo de salvador. Atiende tus propias heridas primero.' }
    }
  },

  // ── Personal Year Meanings (year-long cycle context) ──────
  personalYearMeanings: {
    1: { en: 'A year of fresh starts. You\'re planting seeds for a new 9-year cycle — what you initiate now defines the next chapter.', fr: 'Une année de nouveaux départs. Vous plantez les graines d\'un nouveau cycle de 9 ans — ce que vous initiez maintenant définit le prochain chapitre.', es: 'Un año de nuevos comienzos. Estás plantando semillas para un nuevo ciclo de 9 años — lo que inicies ahora define el próximo capítulo.' },
    2: { en: 'A year of patience and partnership. The seeds planted last year need time to root. Nurture relationships and trust the slow growth.', fr: 'Une année de patience et de partenariat. Les graines plantées l\'an dernier ont besoin de temps pour s\'enraciner. Nourrissez les relations.', es: 'Un año de paciencia y asociación. Las semillas del año pasado necesitan tiempo para enraizar. Nutre las relaciones.' },
    3: { en: 'A year of creative expansion. Self-expression is your superpower this year — write, create, connect, share. Visibility increases.', fr: 'Une année d\'expansion créative. L\'expression de soi est votre superpouvoir cette année — écrivez, créez, connectez, partagez.', es: 'Un año de expansión creativa. La autoexpresión es tu superpoder este año — escribe, crea, conecta, comparte.' },
    4: { en: 'A year of building. Hard work pays dividends now — lay foundations, get organized, commit to the long game. Structure sets you free.', fr: 'Une année de construction. Le travail acharné paie maintenant — posez les fondations, organisez-vous, engagez-vous sur le long terme.', es: 'Un año de construcción. El trabajo duro paga ahora — pon cimientos, organízate, comprométete a largo plazo.' },
    5: { en: 'A year of change and freedom. Expect the unexpected — moves, travel, reinvention. The universe is shaking up what\'s become stale.', fr: 'Une année de changement et de liberté. Attendez-vous à l\'inattendu — déménagements, voyages, réinvention.', es: 'Un año de cambio y libertad. Espera lo inesperado — mudanzas, viajes, reinvención.' },
    6: { en: 'A year of love and responsibility. Family, home, and close relationships take center stage. Commitments deepen or are tested.', fr: 'Une année d\'amour et de responsabilité. Famille, foyer et relations proches sont au premier plan.', es: 'Un año de amor y responsabilidad. Familia, hogar y relaciones cercanas toman el centro del escenario.' },
    7: { en: 'A year of inner work. Pull back from the noise and go deep — study, meditate, question everything. Spiritual growth accelerates.', fr: 'Une année de travail intérieur. Éloignez-vous du bruit et allez en profondeur — étudiez, méditez, questionnez tout.', es: 'Un año de trabajo interior. Aléjate del ruido y profundiza — estudia, medita, cuestiona todo.' },
    8: { en: 'A year of harvest and power. What you\'ve built is ready to bear fruit. Step into authority, negotiate boldly, claim your worth.', fr: 'Une année de récolte et de pouvoir. Ce que vous avez construit est prêt à porter ses fruits. Assumez votre autorité.', es: 'Un año de cosecha y poder. Lo que has construido está listo para dar frutos. Asume tu autoridad.' },
    9: { en: 'A year of completion and release. The 9-year cycle ends. Let go of what\'s run its course — relationships, habits, identities that no longer fit.', fr: 'Une année d\'accomplissement et de libération. Le cycle de 9 ans se termine. Laissez aller ce qui a fait son temps.', es: 'Un año de completación y liberación. El ciclo de 9 años termina. Deja ir lo que ha cumplido su curso.' },
    11: { en: 'A master year of spiritual awakening. Intuitive downloads arrive fast. You\'re being called to a higher purpose — listen and act.', fr: 'Une année maître d\'éveil spirituel. Les téléchargements intuitifs arrivent vite. Vous êtes appelé à un but supérieur.', es: 'Un año maestro de despertar espiritual. Las descargas intuitivas llegan rápido. Estás siendo llamado a un propósito superior.' },
    22: { en: 'A master year of manifestation. You have the rare power to turn vision into reality at scale. Build something that outlasts you.', fr: 'Une année maître de manifestation. Vous avez le pouvoir rare de transformer la vision en réalité à grande échelle.', es: 'Un año maestro de manifestación. Tienes el poder raro de convertir la visión en realidad a gran escala.' },
    33: { en: 'A master year of selfless service. Your capacity to heal and uplift reaches its peak. The world needs what only you can give.', fr: 'Une année maître de service altruiste. Votre capacité à guérir et élever atteint son apogée.', es: 'Un año maestro de servicio altruista. Tu capacidad de sanar y elevar alcanza su punto m��ximo.' }
  },

  // ── Universal Day Meanings (collective energy for everyone) ─
  universalDayMeanings: {
    1: { en: 'The collective energy today favors bold moves and fresh starts. Everyone feels a pull toward independence and initiative.', fr: 'L\'énergie collective aujourd\'hui favorise les coups audacieux et les nouveaux départs. Chacun ressent un élan vers l\'indépendance.', es: 'La energía colectiva hoy favorece movimientos audaces y nuevos comienzos. Todos sienten un impulso hacia la independencia.' },
    2: { en: 'A gentle day in the collective field. Cooperation flows more easily, conflicts find resolution, and small kindnesses ripple outward.', fr: 'Un jour doux dans le champ collectif. La coopération coule plus facilement, les conflits trouvent résolution.', es: 'Un día gentil en el campo colectivo. La cooperación fluye más fácilmente, los conflictos encuentran resolución.' },
    3: { en: 'Creative and social energy fills the collective atmosphere. Communication sparkles, ideas spread, joy is contagious today.', fr: 'L\'énergie créative et sociale remplit l\'atmosphère collective. La communication pétille, les idées se propagent, la joie est contagieuse.', es: 'La energía creativa y social llena la atmósfera colectiva. La comunicación brilla, las ideas se propagan, la alegría es contagiosa.' },
    4: { en: 'The world slows down to do the work today. Practical matters, organization, and methodical progress are favored in the collective.', fr: 'Le monde ralentit pour travailler aujourd\'hui. Les questions pratiques, l\'organisation et le progrès méthodique sont favorisés.', es: 'El mundo se ralentiza para trabajar hoy. Los asuntos prácticos, la organización y el progreso metódico están favorecidos.' },
    5: { en: 'Restless energy courses through the collective. Expect surprises, sudden changes, and a shared hunger for something different.', fr: 'Une énergie agitée parcourt le collectif. Attendez-vous à des surprises, des changements soudains, et une faim partagée de quelque chose de différent.', es: 'La energía inquieta recorre el colectivo. Espera sorpresas, cambios repentinos, y un hambre compartida de algo diferente.' },
    6: { en: 'Love and responsibility pervade the collective mood. People gravitate toward home, family, and acts of care for one another.', fr: 'L\'amour et la responsabilité imprègnent l\'humeur collective. Les gens gravitent vers le foyer, la famille et les actes de soin.', es: 'El amor y la responsabilidad impregnan el ánimo colectivo. La gente gravita hacia el hogar, la familia y los actos de cuidado.' },
    7: { en: 'A reflective day in the collective consciousness. The world turns inward — deep conversations, meaningful questions, and quiet truths surface.', fr: 'Un jour de réflexion dans la conscience collective. Le monde se tourne vers l\'intérieur — conversations profondes et vérités tranquilles émergent.', es: 'Un día reflexivo en la consciencia colectiva. El mundo mira hacia adentro — conversaciones profundas y verdades tranquilas emergen.' },
    8: { en: 'Power and material energy charge the collective today. Financial movements, authority shifts, and ambitious decisions mark this Universal 8 day.', fr: 'Le pouvoir et l\'énergie matérielle chargent le collectif. Mouvements financiers, changements d\'autorité et décisions ambitieuses marquent cette journée.', es: 'El poder y la energía material cargan el colectivo hoy. Movimientos financieros, cambios de autoridad y decisiones ambiciosas marcan este día.' },
    9: { en: 'A day of collective release and compassion. Old structures crumble to make way for new ones. Generosity and forgiveness are in the air.', fr: 'Un jour de libération et de compassion collective. Les vieilles structures s\'effondrent pour faire place aux nouvelles.', es: 'Un día de liberación y compasión colectiva. Las viejas estructuras se desmoronan para dar paso a las nuevas.' },
    11: { en: 'A spiritually charged day for all of humanity. Collective intuition peaks — breakthroughs, revelations, and awakening moments are amplified.', fr: 'Un jour spirituellement chargé pour toute l\'humanité. L\'intuition collective est à son apogée.', es: 'Un día espiritualmente cargado para toda la humanidad. La intuición colectiva alcanza su punto máximo.' },
    22: { en: 'A rare Master Builder day in the collective field. Grand visions can become reality — what the world builds today has lasting significance.', fr: 'Un jour rare de Maître Bâtisseur dans le champ collectif. Les grandes visions peuvent devenir réalité.', es: 'Un raro día de Maestro Constructor en el campo colectivo. Las grandes visiones pueden hacerse realidad.' },
    33: { en: 'The rarest collective energy. A day when healing, compassion, and selfless service reach extraordinary levels across the human field.', fr: 'L\'énergie collective la plus rare. Un jour où la guérison, la compassion et le service altruiste atteignent des niveaux extraordinaires.', es: 'La energía colectiva más rara. Un día donde la sanación, la compasión y el servicio altruista alcanzan niveles extraordinarios.' }
  },

  // ── Get Meaning for a Number ──────────────────────────────
  getMeaning(num) {
    return this.meanings[num] || this.meanings[this.reduce(num)];
  },

  getPersonalYearMeaning(num) {
    return this.personalYearMeanings[num] || this.personalYearMeanings[this.reduce(num)];
  },

  getUniversalDayMeaning(num) {
    return this.universalDayMeanings[num] || this.universalDayMeanings[this.reduce(num)];
  },

  // ── Full Numerology Profile ───────────────────────────────
  getProfile(year, month, day, currentDate = new Date(), fullName = null) {
    const lifePath = this.getLifePath(year, month, day);
    const personalYear = this.getPersonalYear(month, day, currentDate.getFullYear());
    const personalMonth = this.getPersonalMonth(month, day, currentDate);
    const personalDay = this.getPersonalDay(month, day, currentDate);
    const universalDay = this.getUniversalDay(currentDate);

    const profile = {
      lifePath,
      lifePathMeaning: this.getMeaning(lifePath),
      personalYear,
      personalYearMeaning: this.getPersonalYearMeaning(personalYear),
      personalMonth,
      personalMonthMeaning: this.getMeaning(personalMonth),
      personalDay,
      personalDayMeaning: this.getMeaning(personalDay),
      universalDay,
      universalDayMeaning: this.getUniversalDayMeaning(universalDay)
    };

    // Add name-based numbers if name is available
    if (fullName && fullName.trim().length > 1) {
      profile.expression = this.getExpressionNumber(fullName);
      profile.expressionMeaning = this.expressionMeanings[profile.expression] || this.expressionMeanings[this.reduce(profile.expression)];
      profile.soulUrge = this.getSoulUrge(fullName);
      profile.soulUrgeMeaning = this.soulUrgeMeanings[profile.soulUrge] || this.soulUrgeMeanings[this.reduce(profile.soulUrge)];
      profile.personality = this.getPersonalityNumber(fullName);
      profile.personalityMeaning = this.personalityMeanings[profile.personality] || this.personalityMeanings[this.reduce(profile.personality)];
    }

    return profile;
  }
};
